apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
