apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-deployment 
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend
        image: backend-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        
    