apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
spec:
  type: LoadBalancer
  selector:
    app: backend-deployment
  ports:
  - name: backend-deployment
    protocol: TCP
    port: 3001
    targetPort: 3001
